// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR28VwToRmJtXDsIDZyet3uqmiDEZpsnM',
    appId: '1:551379171312:android:720bcbe899e878ca238f35',
    messagingSenderId: '551379171312',
    projectId: 'remote-projector-fc831',
    storageBucket: 'remote-projector-fc831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGwjg6XgMS3ReI03ub4Xgqj6Y5IMxkg-M',
    appId: '1:551379171312:ios:353cdf5283eab447238f35',
    messagingSenderId: '551379171312',
    projectId: 'remote-projector-fc831',
    storageBucket: 'remote-projector-fc831.firebasestorage.app',
    androidClientId: '551379171312-h1q78p9j14qpgn6bf358gssvle1vfbvt.apps.googleusercontent.com',
    iosClientId: '551379171312-n69s3j0k85l3he8vljaumhj8mfchdasm.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteProjector2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjQv1h5GE64uKVfVXoQmhkT7bUmRH9ojE',
    appId: '1:551379171312:web:55f72bdbbe264fc7238f35',
    messagingSenderId: '551379171312',
    projectId: 'remote-projector-fc831',
    authDomain: 'remote-projector-fc831.firebaseapp.com',
    storageBucket: 'remote-projector-fc831.firebasestorage.app',
    measurementId: 'G-SVYXCKRFW8',
  );
}
